import java.util.Map;

rule "Transform Gender"
    agenda-group "Transformations"
    when
        $jsonData: Map(this["Gender"] == 'F')
    then
        $jsonData.put("Gender", "Female");
end

rule "Validate Gender"
    agenda-group "Validations"
    when
        $jsonData: Map(this["Gender"] == null || (this["Gender"] != 'M' && this["Gender"] != 'F'))
    then
        accumulateError($jsonData, "Gender cannot be null or should be 'M' or 'F'", "Gender");
end

rule "Validate Ethnicity"
    agenda-group "Validations"
    when
        $jsonData: Map(this["Ethnicity"] == null || this["Ethnicity"] == 'Unknown')
    then
        accumulateError($jsonData, "Ethnicity cannot be null or 'Unknown'", "Ethnicity");
end
